# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc110bced2f9725734a3aec83dada634f92614a9827753dc38b79a95498c22498e56181a0a17ff1532aa9f85a335e5f22e5a1cf07f0fffe3f023ec8d7531b29

test:
  secret_key_base: 37f59b60d4cf11bcf7ee094b810070b21fc50aec0f29122050c25adb8ebd7b297656955021673f52d541104c7fb3a16cc89791f51ec3d11d3cf0df15b8ff259a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
